burst/burst.py, burst/utils.py, resources/language/English/strings.po, resources/language/Russian/strings.po, resources/language/messages.pot, resources/settings.xml
Can select All, Movies or Serials
When burst takes from the settings included providers, we give him only those that are suitable for the query method.
This reduces the number of requests to sites, increases the search speed, because the script does not attempt to retrieve information from sites that the user has marked for another type of search
=> Add option to providers 'Contain only'.

burst/providers/providers.json
Should be `<tbody>`, so that it only picks `<td>` elements (where the links are).
Currently it also picks the `<th>` element and always prints an "*** Empty name ***" message in the log for it.
=> Improve 1337x parser

burst/providers/providers.json
Hi
rarbg needs a leading zero for the season pack fallback. 
I tested it with a show called "The 100".
This probably applies to some other providers too but I have only tested rarbg.
=> rarbg season fallback needs leading zero

burst/providers/providers.json
During holidays in Linkomanija tracker there is a special event that enables freeleech. This creates a box on the results that announces the event.  Current implementation for the tracker treats the new table as the table with torrents. Therefore, burst returns 0 torrents for search query. The fix is to target the torrent table not by border but by padding.
=> Linkomanija: change target from border to cell padding

burst/filtering.py
in kodi 19
`hashlib.md5()` throws TypeError when get unencoded `result['uri']`
and so for each result returns empty `hash_`
and because of that `filtered_list` contains only one (first) result with empty hash
but there are other different results but with empty hashes.
so, first do python 3 `encode()` (passed in kodi <19)
then `py2_encode()` for kodi <19 - `result['uri']` encoded, kodi 19 no changes
and we have encoded `result['uri']` on both versions and able to successfully generate hash
=> py2_encode do not let generate hash on kodi 19

burst/filtering.py, burst/normalize.py
HTMLParser.unescape was removed from Python since version 3.9.0a1
=> Fix for Python 3.9

resources/language/Croatian/strings.po, resources/language/English/strings.po, resources/language/French/strings.po, resources/language/German/strings.po, resources/language/Hebrew/strings.po, resources/language/Hungarian/strings.po, resources/language/Italian/strings.po, resources/language/Lithuania/strings.po, resources/language/Portuguese (Brazil)/strings.po, resources/language/Portuguese/strings.po, resources/language/Russian/strings.po, resources/language/Spanish (Argentina)/strings.po, resources/language/Spanish (Mexico)/strings.po, resources/language/Spanish/strings.po, resources/language/Swedish/strings.po, resources/language/Ukrainian/strings.po, resources/language/messages.pot, scripts/xgettext_remove_old_messages.sh
Remove old messages and remove them from translations to make code cleaner and to ease work for translators.
tested on kodi 19 with ru lang.
=> Remove old messages

burst/normalize.py
fixes https://github.com/elgatito/script.elementum.burst/issues/259
сломалось тут https://github.com/elgatito/script.elementum.burst/commit/34250fcc3b0512cf1eb7b531ede367a309fef3e4#diff-32510ac0dc8c58a043c69fa5408768bb28ea2e13b74bea5639c654aa121c33dbR69
в данном случае encode() используется не для конвертации строки в строку/байты, как обычно в контексте py2/py3, а для удаления accents.
проверено на русском и французском.
выглядит примерно так
проверено на kodi 17/19
=> Fix remove accents for search

burst/filtering.py, burst/provider.py
добавил `*_extra` для `*_keywords_fallback`, например для поиска в другой категории:
например, сначала ищем сериал в категории сериалы в основных `*_keywords`, 
а потом ищем сериал в категории мультфильмы в `*_keywords_fallback` - чтобы не искать сразу в 2х категориях.
соответственно используем `*_extra` как указатель на категорию, a категорию определяем в `*_query` как `EXTRA`.
ниже есть примеры использования.
=> add support of _fallback_extra

burst/providers/providers.json
Use remove_special_characters in rutor and thepiratebay - see https://github.com/elgatito/script.elementum.burst/issues/263
=> Use remove_special_characters in rutor and thepiratebay

burst/client.py, resources/language/Croatian/strings.po, resources/language/English/strings.po, resources/language/French/strings.po, resources/language/German/strings.po, resources/language/Hebrew/strings.po, resources/language/Hungarian/strings.po, resources/language/Italian/strings.po, resources/language/Lithuania/strings.po, resources/language/Portuguese (Brazil)/strings.po, resources/language/Portuguese/strings.po, resources/language/Russian/strings.po, resources/language/Spanish (Argentina)/strings.po, resources/language/Spanish (Mexico)/strings.po, resources/language/Spanish/strings.po, resources/language/Swedish/strings.po, resources/language/Ukrainian/strings.po, resources/language/messages.pot, resources/settings.xml
- Fixes `Proxy from Elementum settings` setting
Log reported setting applied without really doing anything.
- Adds `Proxy from Elementum (resolve hosts by proxy)` setting option
Option enables default behaviour of `Elementum` in `Burst`. Option is set as new default,
existing users should not be affected by change.
- Adds choice of additional proxy protocols in settings
`SOCKS4a` (`SOCKS4` latest version with hostname resolve by proxy)
`SOCKS5h` (`SOCKS5` latest version with hostname resolve by proxy). Protocol is set as new
default to match default setting in `Elementum`, existing users should not be affected by
change.
- Adds help label for `use_elementum_proxy` setting
=> Proxy settings fixes

resources/language/Russian/strings.po
Чаще всего провайдеров больше 1,  поэтому мн. число
=> минорный фикс

burst/provider.py
There are cases when provider _can_ find some results, but they are later filtered because of different reasons, in my case they had no seeds:
```
2021-08-03 23:31:57.921 T:28768   DEBUG <general>: [script.elementum.burst] [rarbg] >>>>>> rarbg would send 4 torrents to Elementum <<<<<<<
2021-08-03 23:31:57.921 T:28768   DEBUG <general>: [script.elementum.burst] [RARBG] Skipping due to no seeds: 'Its.Always.Sunny.in.Philadelphia.S10E01.WEBRip.x264-ION10'
2021-08-03 23:31:57.921 T:28768   DEBUG <general>: [script.elementum.burst] [RARBG] Skipping due to no seeds: 'Its.Always.Sunny.in.Philadelphia.S10E01.1080p.WEB.x264-CONVOY[rartv]'
2021-08-03 23:31:57.921 T:28768   DEBUG <general>: [script.elementum.burst] [RARBG] Skipping due to no seeds: …
```
=> Cleanup results before adding to the result list

burst/providers/providers.json
Update GloTorrents url
Old base url was: https://www.gtdb.to
New base url is: https://glodls.to
(Basically it works also with "http://" if will be needed)
=> Update GloTorrents url

burst/provider.py
To fix:
```
2023-06-25 14:37:37.493 T:112897   error <general>:   File "/home/user/.kodi/addons/script.elementum.burst/burst/provider.py", line 175, in process
2023-06-25 14:37:37.493 T:112897   error <general>: payload[key] = urllib.unquote(payload[key])
2023-06-25 14:37:37.493 T:112897   error <general>: AttributeError
2023-06-25 14:37:37.493 T:112897   error <general>: module 'urllib' has no attribute 'unquote'
```
when doing search with POST data.
=> Fix post_data unquote error

burst/providers/providers.json
Update torrentfunk parsing and torrent file url.
(Also, slightly improve idope parsing, although it is under Cloudflare protection, so mostly unusable.)
=> fix torrentfunk tracker

burst/burst.py, burst/utils.py
Fix results sorting when allow_noseeds is enabled. Also fix sorting by size.
---
Как я понимаю [`nonesorter` был создан](https://github.com/elgatito/script.elementum.burst/commit/015d61aee9784566019e754383a135aad6e4a989) только для `size`, так как остальные поля у нас всегда становятся int:
`size`:
https://github.com/elgatito/script.elementum.burst/blob/ab939cda886fa95f6c7a39476e9e61fdaffda1c1/burst/provider.py#L45
https://github.com/elgatito/script.elementum.burst/blob/ab939cda886fa95f6c7a39476e9e61fdaffda1c1/burst/utils.py#L280
`seeds`:
https://github.com/elgatito/script.elementum.burst/blob/ab939cda886fa95f6c7a39476e9e61fdaffda1c1/burst/utils.py#L174
`sort_resolution`:
https://github.com/elgatito/script.elementum.burst/blob/ab939cda886fa95f6c7a39476e9e61fdaffda1c1/burst/filtering.py#L64 …
=> Fix results sorting when allow_noseeds, fix sorting by size

burst/parser/ehp.py
in log file:
`critical <general>: [script.elementum.burst] [zamunda] Got an exception while parsing results: AttributeError("'generator' object has no attribute 'next'")`
the fix: https://www.delftstack.com/howto/python/attributeerror-generator-object-has-no-attribute-next/
works with python 2 and 3 - i double checked.
fixes #372.
=> Fix 'generator' object has no attribute 'next'.

burst/burst.py, burst/providers/providers.json
use absolute_episode, use "jp" lang (romanization of Japanese), do not use "|" - unsupported, do not use {season:2}x01 - they do not use it.
this significantly increases number of results without adding wrong results.
example:
```
[script.elementum.burst] -   nyaa query: 'delicious%20in%20dungeon%2006'
[script.elementum.burst] -   nyaa query: 'dungeon%20meshi%2006'
```
=> Improve nyaa anime_keywords

burst/filtering.py, resources/language/Croatian/strings.po, resources/language/English/strings.po, resources/language/French/strings.po, resources/language/German/strings.po, resources/language/Hebrew/strings.po, resources/language/Hungarian/strings.po, resources/language/Italian/strings.po, resources/language/Lithuania/strings.po, resources/language/Portuguese (Brazil)/strings.po, resources/language/Portuguese/strings.po, resources/language/Russian/strings.po, resources/language/Spanish (Argentina)/strings.po, resources/language/Spanish (Mexico)/strings.po, resources/language/Spanish/strings.po, resources/language/Swedish/strings.po, resources/language/Ukrainian/strings.po, resources/language/messages.pot, resources/settings.xml
Option to set 'original' title of Anime to: Original/"Romanization of Japanese"/English.
fixes https://github.com/elgatito/script.elementum.burst/issues/387
fixes https://github.com/elgatito/plugin.video.elementum/issues/987
depends on https://github.com/elgatito/plugin.video.elementum/pull/994
=> Add overwrite_anime_original_title option

burst/burst.py, burst/utils.py
Fix get_setting choices usage in get_enabled_providers.
so now we actually use choices and not strings value of integers (like `"0"`).
depends on https://github.com/elgatito/plugin.video.elementum/pull/994
=> Fix get_setting choices usage in get_enabled_providers

resources/settings.xml
to keep backward compatibility with old way - so nothing will change for users.
also, it anyway makes sense to use translated title by default, since many people want to get "local" releases.
also, many providers that do not support translated queries already have `:en` or `:original` set in queries.
for https://github.com/elgatito/plugin.video.elementum/issues/991
=> Enable kodi_language by default.

burst/filtering.py, resources/language/Croatian/strings.po, resources/language/English/strings.po, resources/language/French/strings.po, resources/language/German/strings.po, resources/language/Hebrew/strings.po, resources/language/Hungarian/strings.po, resources/language/Italian/strings.po, resources/language/Lithuania/strings.po, resources/language/Portuguese (Brazil)/strings.po, resources/language/Portuguese/strings.po, resources/language/Russian/strings.po, resources/language/Spanish (Argentina)/strings.po, resources/language/Spanish (Mexico)/strings.po, resources/language/Spanish/strings.po, resources/language/Swedish/strings.po, resources/language/Ukrainian/strings.po, resources/language/messages.pot, resources/settings.xml
Use included_rx() func for require_keywords, same as for other checks.
So now check logic for "Require" is same as "Accept"/"Block". Also user can use regexp.
I also added detailed help messages.
I had to split help into 2 messages since skin allow maximum 60 characters and 2 lines maximum. And if such lines are close - then then text is overlapping. Thus 1st line on top and 2nd on bottom.
also i removed old patterns that uses `_word_` - this is only supported by old included() func, but this func is a legacy and works strange.
I moved filter_vhsrip in code so now it has the same position as it has in settings.
fixes https://github.com/elgatito/script.elementum.burst/issues/393
=> Use included_rx func for require_keywords, same as for other checks.

burst/provider.py
On passkey based providers (i.e. : Filelist)
Fixes #397
=> Fix strings replacement not occuring on subsequent api calls (passkey based providers)

burst/client.py
Right now if use_elementum_proxy is enabled (and it is enabled by default) then `proxy_enabled` is automatically ignored which is very confusing behavior imho.
Either we should change `elif` to `if` or we should add help that says: "in order to use proxy, you need to disable use_elementum_proxy first".
elif->if just looks as more simple solution but i can also create a help message.
=> proxy_enabled should not be disabled by use_elementum_proxy

burst/filtering.py
Use English as fallback for overwrite_anime_original_title when Romaji is not available.
=> Use English as fallback for overwrite_anime_original_title when Romaji is not available

resources/site-packages/requests/compat.py
after https://github.com/elgatito/script.elementum.burst/pull/416
не стал возвращать ordered_dict.py который для 2,6 так как urllib3 всё равно не работает с 2,6
=> fix requests/compat.py to work on python 2.7

burst/burst.py, burst/filtering.py, burst/normalize.py, burst/parser/HTMLParser.py, burst/provider.py, burst/providers/providers.json, burst/utils.py
it is as a good practice and also Python 3.12 throw warning like `SyntaxWarning: invalid escape sequence '\-'`.
=> Use raw strings for regexp

burst/providers/providers.json, resources/settings.xml
It is dead since June 30 2024 and there is no official reincarnation of this tracker.
https://torrentfreak.com/torrent-site-magnetdl-suffers-extended-downtime-240630/
=> Disable magnetdl as of 02.10.2024

burst/filtering.py
Currently in `included_rx()` we search for keyword without end boundary, so keyword `TS` (from filter_telesync) will match movie called Tsunami and will block it. e.g. https://www.themoviedb.org/search/movie?query=tsunami
Same for other "small" keywords: cam, tc, scr.
So I updated included_rx to search whole keyword to avoid false matches.
Since we add spaces around title (`value = ' ' + value.lower() + ' '`) we can simply use `\W+` - it will match end of word and end of line. (initially i wanted to use `(\W+|$)` or `(?:\W+|$)`)
In the past it also was matched with end boundary - https://github.com/elgatito/script.elementum.burst/commit/67e7e0d86d7b4cf5510ed661d92c59d1669d0adf#diff-78cc99018f5874a1a9641c20d0e5b1d595c3ffa33528e7c7c49fad8e111a0268L68
e.g. it was `_ts_` where `_` was …
=> Fix release types detection to avoid false blocks

burst/burst.py, burst/provider.py
fixes https://github.com/elgatito/script.elementum.burst/issues/417
we can merge this or leave old code as is. up to your liking.
story:
`id` field looks unused. [it was added 3 years ago](https://github.com/elgatito/script.elementum.burst/commit/5945e3d886340c4e226c710609cc4a56bc423fa7), but then i do not see any usage neither in burst or elementum.
for duplicates `hash` is used - https://github.com/elgatito/script.elementum.burst/blob/0de57c95170915e837ec63c42190675ec348562f/burst/filtering.py#L810
in elementum there is no such field for TorrentFile - https://github.com/elgatito/elementum/blame/master/bittorrent/torrent_file.go#L35
maybe it was supposed to be used to find duplicates, but then this idea was abandoned.
after removing all lines added in the commit above - nothing changed …
=> Remove unused "id" field from parser and api_format

burst/providers/providers.json, resources/settings.xml
looks like currently bitsearch has stale data. also looks like torrentz is just a mirror of bitsearch, but it does not matter.
bt4g looks like good replacement of magnetdl.
=> Make bt4g predefined, make bitsearch not predefined.
