- burst/providers/burst_overrides.py
- burst/providers/providers.json
[rutor] Fix search Russian movie. Change search category from 'Зарубежное кино' to 'Любая категория'
[tfile] Correct domain
> Correct rutor & tfile

- burst/providers/providers.json
> fix torrent9 provider

- burst/providers/providers.json
> Update YGG link

- burst/providers/providers.json
With disabled subpage ncore provider works much faster and stable.
> Disable subpage in nCore provider

- burst/providers/providers.json
rutracker.cr is not available anymore, replaced with original *.net host
> original rutracker host

- burst/providers/providers.json
> megapeer.org has moved to megapeer.ru

- burst/providers/providers.json
This is an anonymous PR submitted via Gitmask - https://www.gitmask.com
> Gitmask Anonymous PR

- burst/providers/providers.json
changes in provider linkomanija.net design broke elementum functionality
> fix provider linkomanija.net

- burst/providers/providers.json
Changed color from black (not visible) to red (now visible)  :-)
> Color change

- burst/providers/providers.json
> Update "Il Corsaro Nero"

- burst/providers/providers.json
> Update "Il Corsaro Nero" URL

- addon.xml
- burst/burst.py
- burst/client.py
- burst/filtering.py
- burst/normalize.py
- burst/parser/HTMLParser.py
- burst/parser/ehp.py
- burst/provider.py
- burst/providers/definitions.py
- burst/utils.py
- scripts/antizapret_test.py
- scripts/extract.py
- scripts/generate_settings.py
- scripts/parse_magnetic.py
Make code compatible with python 3
> add python3 support

- burst/providers/providers.json
> Update "ilcorsaronero" URL

- burst/providers/providers.json
> Update "TorrentZ" URL

- burst/providers/providers.json
> Update "GloTorrents" URL

- burst/providers/providers.json
> Update "torrent9" URL

- burst/providers/providers.json
> Update "zamunda" URL

- burst/providers/providers.json
Disabled "SUMOTorrent" since website died
> Disabled "SUMOTorrent" since website died

- burst/providers/providers.json
Update "Zooqle" search separator
> Update "Zooqle" search separator

- burst/providers/providers.json
> Fix "The Pirate Bay"

- burst/providers/providers.json
> Fix for Kickass

- burst/providers/providers.json
> Update "TorrentDownloads" URL

- burst/providers/providers.json
> Update "Sky torrents" URL

- burst/normalize.py
> fix remove_accents for non-ASCII language

- resources/settings.xml
- scripts/generate_settings.py
на основании http://python-future.org/compatible_idioms.html
проверено что py2 и py3 выдают одинаковый результат
плюс убрал лишние пробелы в выходном файле
> make generate_settings.py work for both py2 and py3

- burst/providers/providers.json
update queries for:
1337x
magnetdl
rarbg
thepiratebay
removed unsupported queries and added supported.
> Update providers queries for 1337x/magnetdl/rarbg/thepiratebay

- addon.xml
> use spaces in addon.xml

- resources/language/English/strings.po
- resources/language/German/strings.po
- resources/language/Hebrew/strings.po
- resources/language/Italian/strings.po
- resources/language/Lithuania/strings.po
- resources/language/Portuguese (Brazil)/strings.po
- resources/language/Portuguese/strings.po
- resources/language/Russian/strings.po
- resources/language/Spanish (Argentina)/strings.po
- resources/language/Spanish (Mexico)/strings.po
- resources/language/Spanish/strings.po
- scripts/xgettext_remove_old_messages.sh
```
$ scripts/xgettext.sh
Checking resources/language/Croatian/strings.po                        [  OK  ]
Checking resources/language/English/strings.po                         [  OK  ]
Checking resources/language/French/strings.po                          [  OK  ]
Checking resources/language/German/strings.po                          [  OK  ]
Checking resources/language/Hebrew/strings.po                          [  OK  ]
Checking resources/language/Hungarian/strings.po                       [  OK  ]
Checking resources/language/Italian/strings.po                         [  OK  ]
Checking resources/language/Lithuania/strings.po                       [  OK  ]
Checking resources/language/Portuguese (Brazil)/strings.po             [  OK  ]
Checking resources/language/Portuguese/strings.po …
```
> Cleanup old messages

- burst/providers/providers.json
https://github.com/elgatito/script.elementum.burst/issues/289
Добавление "anime_keywords3": "{title:ru:en} \"TV-{season}\"",  
nnmclub
rustorka
rutracker
> Фикс поиска Аниме в 3ёх торрентах

- burst/providers/providers.json
There are changes in torrents.lt web site, therefore provider stopped working. Corrections in proposed changes fixes the provider.
> Torrent.lt changes in website structure

- burst/providers/providers.json
Update Kickass url
Old base url was: https://katcr.to
New base url is: https://kickasstorrents.to
> Update Kickass url

- burst/providers/providers.json
> Fix itorrent parsing

- burst/providers/providers.json
New base_url: https://www.limetorrents.lol
> Update limetorrents URL

- burst/providers/providers.json
Update parsing, main and torrent file URLs. Fixes #237
> Fix torlock tracker

- burst/providers/providers.json
> fix yourbittorrent

- burst/providers/definitions.py
yet another python3 fix. fixes #349
> Fix load_overrides for python3

- burst/providers/providers.json
**Update 2**: EZTV.LI now redirects to eztvx.to but none of them fetch results.
Help is needed.
> Update EZTVX.to + Fix code

- burst/providers/providers.json
this fixes Torlock provider not returning any results.
> Fix Yourbittorrent, TorrentFunk & Tolock

- resources/language/Ukrainian/strings.po
Github messed up conflict resolving so there's another one.
> Update strings.po uk_ua

- resources/site-packages/urllib3/packages/six.py
file is from https://pypi.org/project/six/#files
> update six.py to avoid future issues with python 2 vs python 3

- burst/providers/providers.json
пропустил прошлый раз ещё одну категорию сериалов.
плюс удалил дубликат поля в другом провайдере, спасибо линтеру.
> improve torrentby shows search

- burst/filtering.py
- burst/utils.py
Support elementum with old get_setting in `use_anime` and fix typo in `get_enabled_providers`.
> Support elementum with old get_setting

- burst/providers/providers.json
- resources/settings.xml
дважды писал их админу, но первый раз получил отписку что типо "много ботов", второй раз без ответа.
Cookie Sync не помог к сожалению.
> Disable torrent.by, it does not work b/c of anti-bot protection

- burst/burst.py
- burst/providers/providers.json
Теперь в имени будет тип раздачи: "Золото", "Серебро", обычная.
https://forum.kinozal.tv/showthread.php?t=63978
https://nnmclub.to/forum/viewtopic.php?t=85699
> Update kinozal & nnmclub & rustorka to show type of "share"

- burst/providers/providers.json
> Fix megapeer as of 27.06.2024

- burst/provider.py
- resources/language/Croatian/strings.po
- resources/language/English/strings.po
- resources/language/French/strings.po
- resources/language/German/strings.po
- resources/language/Hebrew/strings.po
- resources/language/Hungarian/strings.po
- resources/language/Italian/strings.po
- resources/language/Lithuania/strings.po
- resources/language/Portuguese (Brazil)/strings.po
- resources/language/Portuguese/strings.po
- resources/language/Russian/strings.po
- resources/language/Spanish (Argentina)/strings.po
- resources/language/Spanish (Mexico)/strings.po
- resources/language/Spanish/strings.po
- resources/language/Swedish/strings.po
- resources/language/Ukrainian/strings.po
- resources/language/messages.pot
> Show in GUI "login to tracker failed" error

- burst/client.py
- burst/provider.py
- resources/language/Croatian/strings.po
- resources/language/English/strings.po
- resources/language/French/strings.po
- resources/language/German/strings.po
- resources/language/Hebrew/strings.po
- resources/language/Hungarian/strings.po
- resources/language/Italian/strings.po
- resources/language/Lithuania/strings.po
- resources/language/Portuguese (Brazil)/strings.po
- resources/language/Portuguese/strings.po
- resources/language/Russian/strings.po
- resources/language/Spanish (Argentina)/strings.po
- resources/language/Spanish (Mexico)/strings.po
- resources/language/Spanish/strings.po
- resources/language/Swedish/strings.po
- resources/language/Ukrainian/strings.po
- resources/language/messages.pot
- resources/settings.xml
- resources/site-packages/antizapret.py
- resources/site-packages/six.py
- scripts/antizapret_test.py
работает на python3 и python2 (тут было очень много мороки).
основной код на питоне это порт кода на javascript - первую версию мне сделали разные AI, так как я не знаю javascript, а потом уже допиливал. порт кода на javascript - это про разжатие и формирование списков. плюс отдельно ещё скачивание и парсинг самого javascript файла.
тестировал через vpn, так как antizapret работает только для рф. 
лично мне antizapret не нужен, я изначально думал получится быстренько старый код обновить, но не тут то было, там разные хаки с сжатием добавили, чтобы бы хоть как-то вместить 110000 доменов в .pac файл.
в общем, делал ради технического интереса.
пока что, без antizapret в самом elementum - полезно только для трекеров, где мы берём magnet ссылку, из рус яз это только rutor и kinozal. но там ещё …
> Add antizapret

- burst/client.py
- burst/filtering.py
Domain name preferred order:
root_url -> base_url (see update_definitions()) -> public_dns_alias OR tor_dns_alias (see settings.xml) -> user defined alias
> Prefer user defined alias for tracker.
